language: c

matrix:
    include:
      - os: linux
        dist: xenial
      - os: osx

addons:
  apt:
    packages:
    - re2c
    - libsdl2-dev
    - libsdl2-image-dev
    - libfreetype6-dev
  homebrew:
    packages:
    - re2c
    - sdl2
    - sdl2_image
    - freetype

before_script: 
  - mkdir build
  - cd build
  - cmake ..

script: make GSplus
