
.PHONY: rtfm
rtfm:
	@echo ""
	@echo "CMAKE IS NOW USED AS THE BUILD SYSTEM"
	@echo "         (YES I'M YELLING)"
	@echo ""
	@echo "(from top level directory)"
	@echo "  mkdir build"
	@echo "  cd build"
	@echo "  cmake .."
	@echo "  make"
	@echo ""

